CREATE DATABASE kasviordb;
-- drop database kasviordb;

CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(255),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    pin CHAR(6),
    phone_number VARCHAR(13),
    photo VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE wallets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    balance DECIMAL(19, 4) DEFAULT 0,

    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TYPE METHOD_TYPE AS ENUM ('bank', 'online');
CREATE TABLE payment_methods (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    logo VARCHAR(255),
    method METHOD_TYPE,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP
);

INSERT INTO payment_methods
(name, logo, method)
VALUES
('BRI', 'bri.svg', 'bank'),
('DANA', 'dana.svg', 'online'),
('BCA', 'bca.svg', 'bank'),
('GOPAY', 'gopay.svg', 'online'),
('OVO', 'ovo.svg', 'online');

CREATE TYPE TRANSACTION_TYPE AS ENUM ('top-up', 'transfer', 'receive');
CREATE TABLE transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    type TRANSACTION_TYPE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,

    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE topup_details (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT NOT NULL,
    payment_method_id INT NOT NULL,
    discount DECIMAL(19, 4) NOT NULL,
    tax DECIMAL(19, 4) NOT NULL,
    sub_total DECIMAL(19, 4) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,

    FOREIGN KEY (transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id)
);

CREATE TABLE transfer_details (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT NOT NULL,
    recipient_user_id INT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,

    FOREIGN KEY (transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (recipient_user_id) REFERENCES users(id)
);

SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema';
TABLE users;
TABLE wallets;
TABLE transactions;
TABLE payment_methods;
TABLE topup_details;
TABLE transfer_details;

-- Login
SELECT email, password
FROM users
WHERE email = 'anggavb8@gmail.com' AND password = 'password';

-- Register
WITH register AS (
    INSERT INTO users
    (email, password)
    VALUES
    ('anggavb82@gmail.com', 'password')
    RETURNING id
)
INSERT INTO wallets (user_id)
SELECT id FROM register;

-- Get user login information (username, email, photo)
SELECT fullname, email, photo FROM users WHERE id = 1;

-- Get/check user PIN
SELECT pin FROM users WHERE id = 1

-- Get transaction history
(
    SELECT u.fullname, t.type, t.amount
    FROM transactions t
    JOIN users u ON t.user_id = u.id
    WHERE u.id = 1
)
UNION ALL
(
    SELECT u.fullname, 'receive' AS type, t.amount
    FROM transactions t
    JOIN transfer_details td ON t.id = td.transaction_id
    JOIN users u ON t.user_id = u.id
    WHERE u.id = 1
    AND t.type = 'transfer'
);

-- Get user history with option (income/expense, date range)
(
    SELECT
        t.type,
        t.amount,
        t.created_at
    FROM transactions t
    JOIN users u
        ON t.user_id = u.id
    WHERE u.id = 1
    AND (t.type = 'top-up' OR t.type = 'transfer')
)
UNION ALL
(
    SELECT
        'receive' AS type,
        t.amount,
        t.created_at
    FROM transactions t
    JOIN transfer_details td
        ON td.transaction_id = t.id
    JOIN users u
        ON td.recipient_user_id = u.id
    WHERE u.id = 1
    AND t.type = 'transfer'
)
ORDER BY created_at DESC;

-- Get user account information (balance, income, expense)
SELECT
    w.balance,
    (
        SELECT COALESCE(SUM(t.amount), 0)
        FROM transactions t
        JOIN transfer_details td
            ON td.transaction_id = t.id
        WHERE td.recipient_user_id = u.id
        AND t.type = 'transfer'
    )
    +
    (
        SELECT COALESCE(SUM(amount), 0)
        FROM transactions
        WHERE user_id = u.id
        AND type = 'top-up'
    )
    AS income,
    (
        SELECT COALESCE(SUM(amount), 0)
        FROM transactions
        WHERE user_id = u.id
        AND type = 'transfer'
    )
    AS expense
FROM users u
JOIN wallets w ON u.id = w.user_id
WHERE u.id = 1;

-- Find receiver with pagination
SELECT u.fullname AS "receiver"
FROM users u
JOIN transactions t ON u.id = t.user_id
JOIN transfer_details td ON t.id = td.transaction_id
WHERE td.recipient_user_id != 1
AND u.id = 1
LIMIT 10
OFFSET 0;

-- Create transaction/topup
WITH topup AS (
    INSERT INTO transactions (user_id, amount, type)
    VALUES (1, 100000, 'top-up')
    RETURNING id, amount, user_id
),
update_balance AS (
    UPDATE wallets
    SET balance = balance + (SELECT amount FROM topup)
    WHERE id = (SELECT user_id FROM topup)
)
INSERT INTO topup_details (transaction_id, payment_method_id, discount, tax, sub_total)
SELECT id, 1, 5000, 4000, (amount - 5000 + 4000) FROM topup;

-- Get user profile (photo, full name, phone, email)
SELECT photo, fullname, phone_number, email
FROM users
WHERE id = 1;

-- Change pin
UPDATE users
SET pin = '123456',
    updated_at = NOW()
WHERE id = 1;

-- Change password
UPDATE users
SET password = 'newpassword',
    updated_at = NOW()
WHERE id = 1;

-- Change user profile
UPDATE users
SET photo = 'newphoto.img',
    fullname = 'Angga Vb',
    phone_number = '085156770131',
    updated_at = NOW()
WHERE id = 1;